/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment.pkg3;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author AbsoluteCrow
 */

public class Game extends javax.swing.JFrame implements KeyListener
{
    private Player controls = new Player();
    public static DefaultListModel<String> itemsInRoomList = new DefaultListModel<>();
    
    public void keyPressed(KeyEvent k)
    {
        if (k.getKeyCode() == KeyEvent.VK_UP)
        {
            controls.move_up();
        }
        else if (k.getKeyCode() == KeyEvent.VK_LEFT)
        {   
            controls.move_left();            
        }
        else if (k.getKeyCode() == KeyEvent.VK_DOWN)
        {
            controls.move_down();
        }
        else if (k.getKeyCode() == KeyEvent.VK_RIGHT)
        {
            controls.move_right();
        }
    }
    
    public void keyTyped(KeyEvent k)
    {
        
    }
    
    public void keyReleased(KeyEvent k)
    {
        
    }
  
    public static void addToDiary(String string)
    {
        diaryText.append("\n" + string);
    }
    
    public Game()
    {
        initComponents();
        addKeyListener(this);
        tutorialDialog.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        endingDialog = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        restart_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        endingTextEffect = new javax.swing.JTextArea();
        endingTextBag = new javax.swing.JTextField();
        tutorialDialog = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        playerNameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        startGame = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        playerIndicator = new javax.swing.JLabel();
        buttonAddToBag = new javax.swing.JButton();
        scrollBackpack = new javax.swing.JScrollPane();
        backpack = new javax.swing.JTextArea();
        backpackLabel = new javax.swing.JLabel();
        scrollitemRoomList = new javax.swing.JScrollPane();
        itemsGUI = new javax.swing.JList<>();
        itemListLabel = new javax.swing.JLabel();
        addButtonExplain = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        diaryText = new javax.swing.JTextArea();
        diaryLabel = new javax.swing.JLabel();

        endingDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        endingDialog.setTitle("Death by Spook");
        endingDialog.setBackground(new java.awt.Color(250, 250, 250));
        endingDialog.setResizable(false);
        endingDialog.addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosed(java.awt.event.WindowEvent evt)
            {
                endingDialogWindowClosed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        restart_button.setText("Restart");
        restart_button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                restart_buttonActionPerformed(evt);
            }
        });

        endingTextEffect.setEditable(false);
        endingTextEffect.setColumns(20);
        endingTextEffect.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        endingTextEffect.setLineWrap(true);
        endingTextEffect.setRows(5);
        endingTextEffect.setWrapStyleWord(true);
        endingTextEffect.setBorder(null);
        jScrollPane1.setViewportView(endingTextEffect);

        endingTextBag.setEditable(false);
        endingTextBag.setBackground(new java.awt.Color(255, 255, 255));
        endingTextBag.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        endingTextBag.setText("jTextField1");
        endingTextBag.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(restart_button))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                            .addComponent(endingTextBag))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(endingTextBag, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(restart_button)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout endingDialogLayout = new javax.swing.GroupLayout(endingDialog.getContentPane());
        endingDialog.getContentPane().setLayout(endingDialogLayout);
        endingDialogLayout.setHorizontalGroup(
            endingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        endingDialogLayout.setVerticalGroup(
            endingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        endingDialog.pack();
        endingDialog.setLocationRelativeTo(null);

        tutorialDialog.setTitle("Tutorial");
        tutorialDialog.addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                tutorialDialogWindowClosing(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        playerNameField.setText("Skeleton");
        playerNameField.setSelectionStart(0);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to the Spooky House");

        jLabel2.setText("Enter your name below to get spooked.");

        jLabel3.setText("You will begin at the entrance of my very spooky house.");

        jLabel4.setText("To move your character, use the arrow keys on your keyboard.");

        jLabel5.setText("The arrows on the map will correspond to what room your character will move to.");

        startGame.setText("Start Game");
        startGame.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                startGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(startGame)
                        .addGap(264, 264, 264))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(79, 79, 79))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(startGame)
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout tutorialDialogLayout = new javax.swing.GroupLayout(tutorialDialog.getContentPane());
        tutorialDialog.getContentPane().setLayout(tutorialDialogLayout);
        tutorialDialogLayout.setHorizontalGroup(
            tutorialDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tutorialDialogLayout.setVerticalGroup(
            tutorialDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tutorialDialog.pack();
        tutorialDialog.setLocationRelativeTo(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Spooky House");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        playerIndicator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/pkg3/locations/frontdoor.png"))); // NOI18N
        playerIndicator.setToolTipText("");

        buttonAddToBag.setText("Add");
        buttonAddToBag.setFocusable(false);
        buttonAddToBag.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonAddToBagActionPerformed(evt);
            }
        });

        backpack.setEditable(false);
        backpack.setColumns(20);
        backpack.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        backpack.setRows(5);
        backpack.setFocusable(false);
        scrollBackpack.setViewportView(backpack);

        backpackLabel.setText("Backpack");

        itemsGUI.setModel(itemsInRoomList);
        itemsGUI.setToolTipText("");
        itemsGUI.setFocusable(false);
        scrollitemRoomList.setViewportView(itemsGUI);

        itemListLabel.setText("Items in the Room");

        addButtonExplain.setText("Select an item above to add to your bag");

        diaryText.setEditable(false);
        diaryText.setColumns(20);
        diaryText.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        diaryText.setLineWrap(true);
        diaryText.setRows(5);
        diaryText.setWrapStyleWord(true);
        diaryText.setFocusable(false);
        jScrollPane2.setViewportView(diaryText);

        diaryLabel.setText("Skeleton's Diary");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(playerIndicator)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(backpackLabel)
                        .addGap(146, 146, 146))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(itemListLabel)
                        .addGap(126, 126, 126))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonAddToBag, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(scrollitemRoomList, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(addButtonExplain)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(scrollBackpack, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(diaryLabel)
                        .addGap(135, 135, 135))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(playerIndicator)
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(itemListLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollitemRoomList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(addButtonExplain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonAddToBag)
                .addGap(45, 45, 45)
                .addComponent(backpackLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollBackpack, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(diaryLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddToBagActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonAddToBagActionPerformed
    {//GEN-HEADEREND:event_buttonAddToBagActionPerformed
        if (itemsGUI.getSelectedValue() != null)
        {
            controls.explore_items();
            endingDialog.setVisible(true);
        }
    }//GEN-LAST:event_buttonAddToBagActionPerformed

    private void restart_buttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_restart_buttonActionPerformed
    {//GEN-HEADEREND:event_restart_buttonActionPerformed
        controls.execute_restart();
        endingDialog.dispose();
        diaryText.setText("Hello, my name is " + playerNameField.getText() + ". I shall be exploring this house in search of spookiness to squelch.");
    }//GEN-LAST:event_restart_buttonActionPerformed

    private void endingDialogWindowClosed(java.awt.event.WindowEvent evt)//GEN-FIRST:event_endingDialogWindowClosed
    {//GEN-HEADEREND:event_endingDialogWindowClosed
        controls.execute_restart();
    }//GEN-LAST:event_endingDialogWindowClosed

    private void startGameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_startGameActionPerformed
    {//GEN-HEADEREND:event_startGameActionPerformed
        if (playerNameField.getText() != null && !(playerNameField.getText().equals("")))
        {
            controls.setPlayerName(playerNameField.getText());
            diaryLabel.setText(playerNameField.getText() + "'s Diary");
            diaryText.setText("Hello, my name is " + playerNameField.getText() + ". I shall be exploring this house in search of spookiness to squelch.");
            this.setVisible(true);
            tutorialDialog.setVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Name cannot be empty.");
        }
    }//GEN-LAST:event_startGameActionPerformed

    private void tutorialDialogWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_tutorialDialogWindowClosing
    {//GEN-HEADEREND:event_tutorialDialogWindowClosing
        System.exit(0);
    }//GEN-LAST:event_tutorialDialogWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Windows".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Game();                
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addButtonExplain;
    public static javax.swing.JTextArea backpack;
    private javax.swing.JLabel backpackLabel;
    private javax.swing.JButton buttonAddToBag;
    private javax.swing.JLabel diaryLabel;
    private static javax.swing.JTextArea diaryText;
    private javax.swing.JDialog endingDialog;
    public static javax.swing.JTextField endingTextBag;
    public static javax.swing.JTextArea endingTextEffect;
    private javax.swing.JLabel itemListLabel;
    public static javax.swing.JList<String> itemsGUI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel playerIndicator;
    private javax.swing.JTextField playerNameField;
    private javax.swing.JButton restart_button;
    private javax.swing.JScrollPane scrollBackpack;
    private javax.swing.JScrollPane scrollitemRoomList;
    private javax.swing.JButton startGame;
    private javax.swing.JDialog tutorialDialog;
    // End of variables declaration//GEN-END:variables


}

